name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Install poppler-utils
        run: sudo apt-get install -y poppler-utils

      - name: Remove old preview image
        run: rm -f assets/cv-preview.png

      - name: Convert PDF to PNG
        run: pdftoppm -png assets/cv.pdf assets/cv-preview

      - name: Configure git user email
        run: git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configure git user name
        run: git config --local user.name "github-actions[bot]"

      - name: Add PDF and image to git
        run: git add assets/cv.pdf assets/cv-preview-1.png

      - name: Commit changes
        run: git commit -m "Update CV PDF and preview image [skip ci]" || exit 0

      - name: Push changes
        run: git push
