name: build-pdf-and-preview

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Cleanup PDF and preview
        run: |
          rm -f assets/cv-preview.png
          rm -f assets/cv.pdf

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Build preview
        run: |
          sudo apt-get install -y poppler-utils
          pdftoppm -png assets/cv.pdf assets/cv-preview

      - name: Commit and push PDF and preview
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/cv.pdf assets/cv-preview-1.png
          git commit -m "Update CV PDF and preview image [skip ci]" || exit 0
          git push
