name: build-pdf

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Commit and push PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cv.pdf
          git commit -m "Update CV PDF [skip ci]" || exit 0
          git push
